# -*- coding: utf-8 -*-
"""intro to python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DPAZc0r0psWe1PiKWE3mvya3hIWOwQP

## Buatlah sebuah program yang:

   1. Meminta input dari pengguna:

       - Nama mahasiswa

       - NIM mahasiswa

       - Nilai ujian (dalam angka, 0–100)

   2. Cek dan tampilkan tipe data dari setiap input.

   3. Gunakan if-elif-else untuk menentukan kategori nilai, dengan kriteria sebagai berikut:
   
```
Nilai | Kategori
85 - 100 | A (Sangat Baik)
75 - 84 | B (Baik)
60 - 74 | C (Cukup)
40 - 59 | D (Kurang)
< 40 | E (Sangat Kurang)
```

```
==== Ekspektasi Output Jawaban : =====
Masukkan nama mahasiswa: Sarah
Masukkan NIM: 12345678
Masukkan nilai ujian (0-100): 81

Nama: Sarah (type: <class 'str'>)
NIM: 12345678 (type: <class 'str'>)
Nilai: 81 (type: <class 'int'>)

Hasil Evaluasi:
Mahasiswa: Sarah (NIM: 12345678)
Nilai Ujian: 81
Kategori Nilai: B (Baik)
```
"""

# Meminta input nama lengkap dari pengguna dan menyimpannya ke variabel Nama
Nama = input("Masukkan nama lengkap anda:")

# Meminta input NIM dari pengguna dan menyimpannya ke variabel NIM
NIM = input("Sesuaikan NIM dengan yang tertera pada KTM:")

# Meminta input nilai ujian, lalu mengubahnya menjadi tipe data float
Nilai = float(input("Berapa nilai yang anda dapatkan:"))

# Menentukan kategori nilai berdasarkan rentang angka dengan if-elif-else
if 85 <= Nilai <= 100:
    Kategori = "A (Sangat Baik)"
elif 75 <= Nilai <= 84:
    Kategori = "B (Baik)"
elif 60 <= Nilai <= 74:
    Kategori = "C (Cukup)"
elif 40 <= Nilai <= 59:
    Kategori = "D (Kurang)"
else:
    Kategori = "E (Sangat Kurang)"

# Menampilkan hasil input dan hasil evaluasi kategori nilai
print("Nama:", Nama)
print("NIM:", NIM)
print("Nilai:", Nilai)
print("Kategori nilai:", Kategori)